In [1]:
import pandas as pd

import tensorflow_hub as hub 

import tensorflow_text as text

from keras.layers import Input ,Dense,Dropout

import tensorflow as tf

import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

C:\Users\mohan\AppData\Local\Temp\ipykernel_14160\186230248.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [5]:
data = pd.read_csv(r"Genre Classification Dataset\train_data.txt",header=None ,delimiter= " ::: ", names= ["id","name","genre","story"])

C:\Users\mohan\AppData\Local\Temp\ipykernel_14160\1826572014.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data = pd.read_csv(r"Genre Classification Dataset\train_data.txt",header=None ,delimiter= " ::: ", names= ["id","name","genre","story"])


In [6]:
data.head()

id                              name     genre  \
0   1      Oscar et la dame rose (2009)     drama   
1   2                      Cupid (1997)  thriller   
2   3  Young, Wild and Wonderful (1980)     adult   
3   4             The Secret Sin (1915)     drama   
4   5            The Unrecovered (2007)     drama   

                                               story  
0  Listening in to a conversation between his doc...  
1  A brother and sister with a past incestuous re...  
2  As the bus empties the students for their fiel...  
3  To help their unemployed father make ends meet...  
4  The film's title refers not only to the un-rec...

In [7]:
genre_names = data["genre"].unique()
genre_names

array(['drama', 'thriller', 'adult', 'documentary', 'comedy', 'crime',
       'reality-tv', 'horror', 'sport', 'animation', 'action', 'fantasy',
       'short', 'sci-fi', 'music', 'adventure', 'talk-show', 'western',
       'family', 'mystery', 'history', 'news', 'biography', 'romance',
       'game-show', 'musical', 'war'], dtype=object)

In [8]:
genre_id_dict = dict()

for i,name in enumerate(genre_names):

    genre_id_dict[name] = i


In [9]:
def giveId(name):

    rerurngenre_id_dict

    

In [10]:
data["genre"] = data["genre"].apply(lambda x : genre_id_dict[x] )

In [11]:
distributed_data = distributed_data.sample(frac=1)
distributed_data.head()

NameError: name 'distributed_data' is not defined

In [56]:
distributed_data["genre"].value_counts()

genre
19    132
26    132
18    132
13    132
6     132
14    132
5     132
20    132
22    132
1     132
10    132
21    132
0     132
15    132
12    132
24    132
2     132
8     132
25    132
23    132
16    132
7     132
3     132
9     132
4     132
11    132
17    132
Name: count, dtype: int64

In [12]:
preprocesser = hub.KerasLayer("https://kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-uncased-preprocess/versions/3")
encoder = hub.KerasLayer("https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/bert-en-uncased-l-10-h-128-a-2/versions/2",trainable=True)

In [13]:
pre_data = preprocesser(data["story"])

In [14]:
data = encoder(pre_data)

In [38]:
x = np.array(data["pooled_output"])
y = np.array(distributed_data["genre"],dtype=np.float32)

In [40]:
len(y)

3564

In [16]:
x[:5]

array([["A simple low budget piece about the relationship between a young musician (making a living as a garbage collector) and the traumatized girl he finds 'on a trash heap.' Shot digitally, the film elaborates the atmosphere of their burgeoning emotional bond but focuses above all on creating an intimately authentic portrayal of the protagonists. The music of 'Ivan Král' (qv) adds an important texture to the movie."],
       ['Eddie Linda and Jimmy stumble into a back alley exchange and a world of problems. What they steal defies all logic, reasoning and leads them into a years old massacre, a government conspiracy, a made man, a glitzy preacher and a transvestite with a song. Eddie, Linda and Jimmy and use their spectacularly average intelligence and cavalier attitudes about life to untangle the web they have spun for themselves to its unavoidable end.'],
       ['"Rain Man Show" is a talk format show led by filmmaker and radio personality Michael Flores and co-hosted by Tony Sabal

In [17]:
y[:5]

array([23., 13., 16.,  9., 12.], dtype=float32)

In [43]:
train_x , test_x , train_y, test_y = train_test_split(x,y,test_size=0.2)

In [19]:
train_y

array([[25.],
       [ 3.],
       [21.],
       ...,
       [ 6.],
       [15.],
       [12.]], dtype=float32)

In [44]:
model = LogisticRegression(max_iter=40000)
model.fit(train_x,train_y)

LogisticRegression(max_iter=40000)

In [45]:
model.score(test_x,test_y)

0.2720897615708275

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

def get_top_n_bigram(corpus, n=None):
    vec = CountVectorizer(ngram_range=(2, 2)).fit(corpus)
    bag_of_words = vec.transform(corpus)
    print(bag_of_words.toarray())
    sum_words = bag_of_words.sum(axis=0) 
    print(sum_words)
    print(vec.vocabulary_.items())
    words_freq = [(word, sum_words[0, idx]) for word, idx in vec.vocabulary_.items()]
    words_freq = sorted(words_freq, key=lambda x: x[1], reverse=True)
    return words_freq[:n]

# Example corpus
corpus = [
    "This is a simple example.",
    "Another example to illustrate.",
    "Let's see how this is function works."
]

# Get the top 3 bigrams
top_bigrams = get_top_n_bigram(corpus, n=3)

# Display the result
print("Top 3 Bigrams:")
for bigram, frequency in top_bigrams:
    print(f"{bigram}: {frequency}")


[[0 0 0 0 0 1 0 0 1 1 0]
 [1 1 0 0 0 0 0 0 0 0 1]
 [0 0 1 1 1 0 1 1 0 1 0]]
[[1 1 1 1 1 1 1 1 1 2 1]]
dict_items([('this is', 9), ('is simple', 5), ('simple example', 8), ('another example', 0), ('example to', 1), ('to illustrate', 10), ('let see', 6), ('see how', 7), ('how this', 3), ('is function', 4), ('function works', 2)])
Top 3 Bigrams:
this is: 2
is simple: 1
simple example: 1
